name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: First step
        run: echo "Run HelloWorld.java"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Check java version
        if: ${{success()}}
        run: |
            java --version
            javac --version

      - name: Run HelloWorld.java
        run: |
            javac src/HelloWorld.java
            java src/HelloWorld.java
