name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - env: stg
            s3: stg-s3
          - env: prod
            s3: prod-s3
    steps:
      - name: Show env
        run: |
           echo "env: ${{ matrix.env }}"
      - name: Show s3 name
        run: |
           echo "env: ${{ matrix.s3 }}"
  build:
     runs-on: ubuntu-20.04
     steps:
      - name: Show s3 name
        run: |
           echo "build"
