name: hello-world
on: push
jobs:
  setup-env:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - env: stg
            s3: stg-s3
          - env: prod
            s3: prod-s3
    steps:
      - name: notify
        run: |
           echo "start build"
      - name: Show env
        run: |
           echo "env: ${{ matrix.env }}"
           if [ ${{ matrix.env }} == "stg" ]; then echo "111111111111"; fi
      - name: Show s3 name
        run: |
           echo "env: ${{ matrix.s3 }}"
  build:
     runs-on: ubuntu-20.04
     needs: setup-env
     steps:
      - name: Show s3 name
        run: |
           echo "build"
