name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        env: [stg, prod]
    steps:
      - name: Show env
        run: |
           echo "env: ${{ matrix.env }}"
